spring:
  application:
    name: PostService
  datasource:
    url: jdbc:postgresql://msitp.postgres.database.azure.com:5432/postgres
    username: msadmin
    password: itpadmin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect